#
# This workflow will run all the normal static tests (linting, unit, etc.) and
# make sure the build completes successfully.
#

name: test

on:
  push:
    branches: [ 'feature/*' ]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g pnpm@^6.32.9
    - run: pnpm i
    - run: pnpm run test
    - run: pnpm run make
      env:
        STAGE: local
